export const TestData = [
  {
    id: "1",
    name: "Kittu Vamsi",
    username: "kittu_v",
    email: "kittu.vamsi@example.com",
    phone: "+91-9876543210",
    age: 24,
    gender: "Male",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    country: "India",
    postalCode: "530017",
    occupation: "Software Engineer",
    company: "TechNova Solutions",
    department: "Engineering",
    salary: 75000,
    joinDate: "2022-05-14",
    lastLogin: "2025-10-30T14:25:00Z",
    isActive: true,
    skills: ["React", "Node.js", "MongoDB"],
  },
  {
    id: "2",
    name: "Ravi Kumar",
    username: "ravi_k",
    email: "ravi.kumar@example.com",
    phone: "+91-9123456789",
    age: 29,
    gender: "Male",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    postalCode: "500081",
    occupation: "Data Analyst",
    company: "Insight Corp",
    department: "Analytics",
    salary: 62000,
    joinDate: "2021-09-03",
    lastLogin: "2025-10-27T09:10:00Z",
    isActive: false,
    skills: ["SQL", "Python", "Power BI"],
  },
  {
    id: "3",
    name: "Sita Reddy",
    username: "sita_r",
    email: "sita.reddy@example.com",
    phone: "+91-9345678901",
    age: 26,
    gender: "Female",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    postalCode: "600034",
    occupation: "Teacher",
    company: "Springdale High School",
    department: "Education",
    salary: 42000,
    joinDate: "2020-06-21",
    lastLogin: "2025-11-01T12:00:00Z",
    isActive: true,
    skills: ["English", "Curriculum Planning", "Communication"],
  },
  {
    id: "4",
    name: "Anu Sharma",
    username: "anu_s",
    email: "anu.sharma@example.com",
    phone: "+91-9567890123",
    age: 31,
    gender: "Female",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    postalCode: "560001",
    occupation: "UI/UX Designer",
    company: "PixelCraft Studios",
    department: "Design",
    salary: 85000,
    joinDate: "2023-02-10",
    lastLogin: "2025-10-25T11:20:00Z",
    isActive: true,
    skills: ["Figma", "Adobe XD", "User Research"],
  },
  {
    id: "5",
    name: "Manoj Patel",
    username: "manoj_p",
    email: "manoj.patel@example.com",
    phone: "+91-9456789012",
    age: 28,
    gender: "Male",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postalCode: "400001",
    occupation: "Marketing Manager",
    company: "AdSphere Media",
    department: "Marketing",
    salary: 95000,
    joinDate: "2019-11-17",
    lastLogin: "2025-10-29T08:30:00Z",
    isActive: false,
    skills: ["SEO", "Google Ads", "Campaign Strategy"],
  },
  {
    id: "6",
    name: "Priya Nair",
    username: "priya_n",
    email: "priya.nair@example.com",
    phone: "+91-9891234567",
    age: 25,
    gender: "Female",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    postalCode: "110001",
    occupation: "Doctor",
    company: "Apollo Hospitals",
    department: "Healthcare",
    salary: 120000,
    joinDate: "2020-08-09",
    lastLogin: "2025-10-31T19:00:00Z",
    isActive: true,
    skills: ["Diagnosis", "Patient Care", "Surgery"],
  },
  {
    id: "7",
    name: "Rahul Deshmukh",
    username: "rahul_d",
    email: "rahul.deshmukh@example.com",
    phone: "+91-9786543210",
    age: 30,
    gender: "Male",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    postalCode: "411001",
    occupation: "Civil Engineer",
    company: "BuildTech Pvt Ltd",
    department: "Construction",
    salary: 68000,
    joinDate: "2021-03-14",
    lastLogin: "2025-11-02T16:45:00Z",
    isActive: true,
    skills: ["AutoCAD", "Project Planning", "Estimation"],
  },
  {
    id: "8",
    name: "Sneha Roy",
    username: "sneha_r",
    email: "sneha.roy@example.com",
    phone: "+91-9988776655",
    age: 27,
    gender: "Female",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    postalCode: "700001",
    occupation: "Graphic Designer",
    company: "Creative Ink Studio",
    department: "Design",
    salary: 72000,
    joinDate: "2022-11-01",
    lastLogin: "2025-10-30T13:15:00Z",
    isActive: true,
    skills: ["Photoshop", "Illustrator", "Brand Design"],
  },
  {
    id: "9",
    name: "Vamsi Krishna",
    username: "vamsi_k",
    email: "vamsi.krishna@example.com",
    phone: "+91-9709876543",
    age: 23,
    gender: "Male",
    city: "Guntur",
    state: "Andhra Pradesh",
    country: "India",
    postalCode: "522002",
    occupation: "Student",
    company: "N/A",
    department: "Education",
    salary: 0,
    joinDate: "2024-07-01",
    lastLogin: "2025-10-28T18:00:00Z",
    isActive: true,
    skills: ["Python", "JavaScript", "Machine Learning"],
  },
  {
    id: "10",
    name: "Teja Reddy",
    username: "teja_r",
    email: "teja.reddy@example.com",
    phone: "+91-9945123456",
    age: 32,
    gender: "Male",
    city: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    postalCode: "517501",
    occupation: "Entrepreneur",
    company: "RedLeaf Ventures",
    department: "Management",
    salary: 150000,
    joinDate: "2018-01-25",
    lastLogin: "2025-10-26T10:00:00Z",
    isActive: false,
    skills: ["Leadership", "Finance", "Business Strategy"],
  },
];
